"""Marcação de conteúdo gerado por IA — uma convenção só, aplicada em todos os pontos.

**A cor nunca vem sozinha.** Toda marcação carrega o selo textual `t("ai.badge")`. Usuários
com daltonismo e qualquer impressão em preto e branco perdem a cor; a informação de que aquele
texto foi escrito por um modelo não pode se perder junto. Isso é honestidade científica, não
acessibilidade opcional.

Convenção: **faixa vertical amarela de 6 px na borda esquerda + selo "IA" no topo**. A escolha
da borda em vez do plano de fundo está justificada em `docs/inventario-ia.md` — em resumo:
texto longo sobre amarelo cansa, e a faixa lateral sobrevive a export monocromático.
"""

from __future__ import annotations

import customtkinter as ctk

from core.i18n import t
from ui.design_tokens import INK, WHITE_CARD, YELLOW

#: Largura da faixa lateral. Fina o bastante para não competir com o conteúdo, grossa o
#: bastante para sobreviver a um export reduzido.
LARGURA_FAIXA = 6

#: Prefixo textual usado nos EXPORTS. A cor não viaja para Markdown nem para PDF.
PREFIXO_EXPORT = "[IA]"

NOTA_RODAPE_EXPORT = {
    "pt_BR": ("As seções marcadas com [IA] foram geradas por um modelo de linguagem a partir "
              "dos dados do corpus. Confira antes de citar."),
    "en":    ("Sections marked with [IA] were generated by a language model from the corpus "
              "data. Verify before citing."),
    "fr":    ("Les sections marquées [IA] ont été générées par un modèle de langage à partir "
              "des données du corpus. Vérifiez avant de citer."),
}


def selo_ia(master, **kw) -> ctk.CTkLabel:
    """O selo textual. Curto, chapado, canto zero — e obrigatório onde houver amarelo."""
    return ctk.CTkLabel(master, text=t("ai.badge"), fg_color=YELLOW, text_color=INK,
                        font=ctk.CTkFont(size=11, weight="bold"), corner_radius=0,
                        padx=6, **kw)


class AIContentFrame(ctk.CTkFrame):
    """Bloco de conteúdo gerado por IA: faixa amarela à esquerda, selo no topo.

    Quem usa põe o conteúdo em `.corpo`, que é um frame comum sobre o card branco — o texto
    **não** fica sobre o amarelo, só o selo fica.
    """

    def __init__(self, master, **kw):
        kw.setdefault("fg_color", WHITE_CARD)
        kw.setdefault("corner_radius", 0)
        super().__init__(master, **kw)

        self.faixa = ctk.CTkFrame(self, width=LARGURA_FAIXA, fg_color=YELLOW,
                                  corner_radius=0)
        self.faixa.pack(side="left", fill="y")
        self.faixa.pack_propagate(False)

        interno = ctk.CTkFrame(self, fg_color="transparent")
        interno.pack(side="left", fill="both", expand=True, padx=10, pady=8)

        cabecalho = ctk.CTkFrame(interno, fg_color="transparent")
        cabecalho.pack(anchor="w", fill="x")
        self.selo = selo_ia(cabecalho)
        self.selo.pack(side="left")

        self.corpo = ctk.CTkFrame(interno, fg_color="transparent")
        self.corpo.pack(fill="both", expand=True, pady=(6, 0))


def marcar_texto_export(titulo: str) -> str:
    """Título de seção → título marcado, para Markdown/PDF.

    Idempotente: chamar duas vezes não empilha prefixos.
    """
    titulo = (titulo or "").strip()
    if titulo.startswith(PREFIXO_EXPORT):
        return titulo
    return f"{PREFIXO_EXPORT} {titulo}".strip()


def nota_rodape_export(lang: str | None = None) -> str:
    """Nota explicando o marcador, no idioma da UI. Vai no fim de todo export com IA."""
    if lang is None:
        try:
            from core.i18n import get_lang
            lang = get_lang()
        except Exception:
            lang = "pt_BR"
    return NOTA_RODAPE_EXPORT.get(lang, NOTA_RODAPE_EXPORT["en"])


def rotulo_cluster_e_de_ia(cluster_id, origens: dict | None) -> bool:
    """O rótulo deste cluster veio da IA ou foi escrito pelo usuário?

    Rótulo que o usuário editou à mão **deixa de ser** conteúdo de IA — passa a ser dado dele.
    Marcar como IA algo que a pessoa escreveu seria tão errado quanto o inverso.
    """
    if not origens:
        return False
    # Busca nos dois sentidos: o id nasce inteiro no Louvain, vira texto ao passar pelo JSON
    # do projeto, e as duas formas circulam no app. Procurar só numa delas faz a marcação
    # sumir depois de salvar e reabrir — o pior tipo de falha, porque parece intermitente.
    for chave in (cluster_id, str(cluster_id)):
        if chave in origens:
            return str(origens[chave] or "").lower() == "ia"
    try:
        numerica = int(cluster_id)
    except (TypeError, ValueError):
        return False
    return str(origens.get(numerica) or "").lower() == "ia"
